//! `tractus init` — one-time, idempotent setup.
//!
//! Two steps are currently manual and easy to get wrong: generating the
//! machine-local `.codex/hooks.json` and enabling the experimental hook feature
//! flag in `~/.codex/config.toml`. `init` performs both, verifies the sibling
//! binaries exist, and prints exactly what it changed. Every step is safe to run
//! repeatedly: unchanged files are left untouched and the global config is backed
//! up before any edit.

use std::env;
use std::error::Error;
use std::fmt;
use std::fs;
use std::io::{self, Write};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use toml_edit::{value, DocumentMut, Item, Table};

const WRAPPER_RELATIVE: &str = ".codex/run-ct-hook.sh";
const HOOKS_RELATIVE: &str = ".codex/hooks.json";
const REQUIRED_BINARIES: &[&str] = &["chaosd", "ct-hook"];

/// Resolve the repository and global config paths, then run setup.
pub fn run_init<W: Write>(output: &mut W) -> Result<(), InitError> {
    let repo_root = locate_repo_root()?;
    let config_path = codex_config_path()?;
    init_with_paths(&repo_root, &config_path, output)
}

fn init_with_paths<W: Write>(
    repo_root: &Path,
    config_path: &Path,
    output: &mut W,
) -> Result<(), InitError> {
    writeln!(output, "TRACTUS ▸ init")?;
    writeln!(output, "Repository: {}", repo_root.display())?;
    writeln!(output)?;

    let hook = install_hook(repo_root)?;
    match hook.changed {
        true => writeln!(
            output,
            "✓ Codex hook installed: {}",
            hook.hooks_file.display()
        )?,
        false => writeln!(
            output,
            "✓ Codex hook already installed: {}",
            hook.hooks_file.display()
        )?,
    }

    let flag = enable_hook_feature(config_path)?;
    match &flag {
        FlagOutcome::AlreadyEnabled { path } => {
            writeln!(output, "✓ Hook feature already enabled: {}", path.display())?
        }
        FlagOutcome::Created { path } => writeln!(
            output,
            "✓ Hook feature enabled (created {})",
            path.display()
        )?,
        FlagOutcome::Updated { path, backup } => writeln!(
            output,
            "✓ Hook feature enabled: {} (backup at {})",
            path.display(),
            backup.display()
        )?,
    }

    let binaries = check_binaries(repo_root);
    let mut missing = Vec::new();
    for binary in &binaries {
        match &binary.path {
            Some(path) => writeln!(output, "✓ {} present: {}", binary.name, path.display())?,
            None => {
                writeln!(output, "• {} not built yet", binary.name)?;
                missing.push(binary.name);
            }
        }
    }

    writeln!(output)?;
    if missing.is_empty() {
        writeln!(
            output,
            "Setup complete. Next: run `tractus` to create or pick a contract and launch Codex."
        )?;
    } else {
        writeln!(
            output,
            "Almost there — build the missing binaries with `cargo build --release`, then run `tractus`."
        )?;
    }
    Ok(())
}

/// Walk up from the running executable and the working directory looking for the
/// committed hook wrapper, which marks the repository root.
fn locate_repo_root() -> Result<PathBuf, InitError> {
    let mut starts: Vec<PathBuf> = Vec::new();
    if let Ok(exe) = env::current_exe() {
        if let Some(dir) = exe.parent() {
            starts.push(dir.to_path_buf());
        }
    }
    if let Ok(cwd) = env::current_dir() {
        starts.push(cwd);
    }
    for start in starts {
        let mut current: Option<&Path> = Some(start.as_path());
        while let Some(dir) = current {
            if dir.join(WRAPPER_RELATIVE).is_file() {
                return Ok(dir.to_path_buf());
            }
            current = dir.parent();
        }
    }
    Err(InitError::RepoRootNotFound)
}

struct HookOutcome {
    hooks_file: PathBuf,
    changed: bool,
}

fn install_hook(repo_root: &Path) -> Result<HookOutcome, InitError> {
    let wrapper = repo_root.join(WRAPPER_RELATIVE);
    let hooks_file = repo_root.join(HOOKS_RELATIVE);
    if !wrapper.is_file() {
        return Err(InitError::WrapperMissing { path: wrapper });
    }
    ensure_executable(&wrapper)?;

    let desired = hooks_json(&wrapper);
    let changed = match fs::read_to_string(&hooks_file) {
        Ok(existing) if existing == desired => false,
        _ => {
            write_file(&hooks_file, &desired)?;
            true
        }
    };
    Ok(HookOutcome {
        hooks_file,
        changed,
    })
}

fn hooks_json(wrapper: &Path) -> String {
    let document = serde_json::json!({
        "_comment": "generated by `tractus init` — do not edit",
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash|apply_patch",
                    "hooks": [
                        { "type": "command", "command": wrapper.to_string_lossy() }
                    ]
                }
            ]
        }
    });
    let mut rendered =
        serde_json::to_string_pretty(&document).expect("a fixed JSON structure always serializes");
    rendered.push('\n');
    rendered
}

fn ensure_executable(path: &Path) -> Result<(), InitError> {
    let metadata = fs::metadata(path).map_err(|source| InitError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    let mut permissions = metadata.permissions();
    let mode = permissions.mode();
    if mode & 0o100 == 0 {
        permissions.set_mode(mode | 0o755);
        fs::set_permissions(path, permissions).map_err(|source| InitError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    }
    Ok(())
}

enum FlagOutcome {
    AlreadyEnabled { path: PathBuf },
    Created { path: PathBuf },
    Updated { path: PathBuf, backup: PathBuf },
}

fn enable_hook_feature(config_path: &Path) -> Result<FlagOutcome, InitError> {
    if !config_path.exists() {
        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent).map_err(|source| InitError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        write_file(config_path, "[features]\nhooks = true\n")?;
        return Ok(FlagOutcome::Created {
            path: config_path.to_path_buf(),
        });
    }

    let existing = fs::read_to_string(config_path).map_err(|source| InitError::Io {
        path: config_path.to_path_buf(),
        source,
    })?;
    let mut document =
        existing
            .parse::<DocumentMut>()
            .map_err(|source| InitError::ConfigParse {
                path: config_path.to_path_buf(),
                source,
            })?;

    if hooks_already_enabled(&document) {
        return Ok(FlagOutcome::AlreadyEnabled {
            path: config_path.to_path_buf(),
        });
    }

    set_hooks_flag(&mut document);
    let backup = backup_path(config_path);
    fs::copy(config_path, &backup).map_err(|source| InitError::Io {
        path: backup.clone(),
        source,
    })?;
    write_file(config_path, &document.to_string())?;
    Ok(FlagOutcome::Updated {
        path: config_path.to_path_buf(),
        backup,
    })
}

fn hooks_already_enabled(document: &DocumentMut) -> bool {
    document
        .get("features")
        .and_then(Item::as_table)
        .and_then(|features| features.get("hooks"))
        .and_then(Item::as_bool)
        == Some(true)
}

fn set_hooks_flag(document: &mut DocumentMut) {
    let table = document.as_table_mut();
    let features = table
        .entry("features")
        .or_insert_with(|| Item::Table(Table::new()));
    match features.as_table_mut() {
        Some(features_table) => {
            features_table.insert("hooks", value(true));
        }
        None => {
            let mut features_table = Table::new();
            features_table.insert("hooks", value(true));
            *features = Item::Table(features_table);
        }
    }
}

fn backup_path(config_path: &Path) -> PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or_default();
    let name = config_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("config.toml");
    config_path.with_file_name(format!("{name}.tractus-bak-{stamp}"))
}

struct BinaryStatus {
    name: &'static str,
    path: Option<PathBuf>,
}

fn check_binaries(repo_root: &Path) -> Vec<BinaryStatus> {
    let exe_dir = env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(Path::to_path_buf));

    REQUIRED_BINARIES
        .iter()
        .map(|name| {
            let mut candidates = Vec::new();
            if let Some(dir) = &exe_dir {
                candidates.push(dir.join(name));
            }
            candidates.push(repo_root.join("target/release").join(name));
            candidates.push(repo_root.join("target/debug").join(name));
            let path = candidates.into_iter().find(|candidate| candidate.is_file());
            BinaryStatus { name, path }
        })
        .collect()
}

fn codex_config_path() -> Result<PathBuf, InitError> {
    if let Some(dir) = env::var_os("CODEX_HOME").filter(|value| !value.is_empty()) {
        return Ok(PathBuf::from(dir).join("config.toml"));
    }
    let home = env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .ok_or(InitError::HomeNotFound)?;
    Ok(PathBuf::from(home).join(".codex").join("config.toml"))
}

fn write_file(path: &Path, contents: &str) -> Result<(), InitError> {
    fs::write(path, contents).map_err(|source| InitError::Io {
        path: path.to_path_buf(),
        source,
    })
}

#[derive(Debug)]
pub enum InitError {
    Io {
        path: PathBuf,
        source: io::Error,
    },
    Output(io::Error),
    RepoRootNotFound,
    HomeNotFound,
    WrapperMissing {
        path: PathBuf,
    },
    ConfigParse {
        path: PathBuf,
        source: toml_edit::TomlError,
    },
}

impl fmt::Display for InitError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => {
                write!(formatter, "I/O error at {}: {source}", path.display())
            }
            Self::Output(source) => write!(formatter, "could not write init output: {source}"),
            Self::RepoRootNotFound => write!(
                formatter,
                "could not find the Tractus repository (looked for {WRAPPER_RELATIVE}); run init from inside the project"
            ),
            Self::HomeNotFound => write!(
                formatter,
                "neither CODEX_HOME nor HOME is set; cannot locate ~/.codex/config.toml"
            ),
            Self::WrapperMissing { path } => write!(
                formatter,
                "hook wrapper is missing: {}; the repository checkout is incomplete",
                path.display()
            ),
            Self::ConfigParse { path, source } => write!(
                formatter,
                "could not parse Codex config {}: {source}",
                path.display()
            ),
        }
    }
}

impl From<io::Error> for InitError {
    fn from(error: io::Error) -> Self {
        Self::Output(error)
    }
}

impl Error for InitError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Output(source) => Some(source),
            Self::ConfigParse { source, .. } => Some(source),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static NEXT_TEST_DIRECTORY: AtomicUsize = AtomicUsize::new(0);

    struct TestRepo {
        root: PathBuf,
    }

    impl TestRepo {
        fn new() -> Self {
            let sequence = NEXT_TEST_DIRECTORY.fetch_add(1, Ordering::Relaxed);
            let root = env::temp_dir().join(format!(
                "tractus-init-test-{}-{sequence}",
                std::process::id()
            ));
            fs::create_dir_all(root.join(".codex")).unwrap();
            fs::write(root.join(WRAPPER_RELATIVE), "#!/bin/sh\n").unwrap();
            let mut permissions = fs::metadata(root.join(WRAPPER_RELATIVE))
                .unwrap()
                .permissions();
            permissions.set_mode(0o644);
            fs::set_permissions(root.join(WRAPPER_RELATIVE), permissions).unwrap();
            Self { root }
        }
    }

    impl Drop for TestRepo {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    #[test]
    fn installs_hook_and_creates_config_when_absent() {
        let repo = TestRepo::new();
        let config = repo.root.join("codex-home").join("config.toml");
        let mut output = Vec::new();

        init_with_paths(&repo.root, &config, &mut output).unwrap();

        let hooks = fs::read_to_string(repo.root.join(HOOKS_RELATIVE)).unwrap();
        assert!(hooks.contains(
            &repo
                .root
                .join(WRAPPER_RELATIVE)
                .to_string_lossy()
                .into_owned()
        ));
        assert!(hooks.contains("Bash|apply_patch"));
        assert_eq!(
            fs::read_to_string(&config).unwrap(),
            "[features]\nhooks = true\n"
        );
        // The wrapper must end up executable for Codex to run it.
        let mode = fs::metadata(repo.root.join(WRAPPER_RELATIVE))
            .unwrap()
            .permissions()
            .mode();
        assert_ne!(mode & 0o100, 0);
    }

    #[test]
    fn is_idempotent_on_second_run() {
        let repo = TestRepo::new();
        let config = repo.root.join("config.toml");
        let mut first = Vec::new();
        init_with_paths(&repo.root, &config, &mut first).unwrap();

        let hooks_before = fs::read_to_string(repo.root.join(HOOKS_RELATIVE)).unwrap();
        let config_before = fs::read_to_string(&config).unwrap();

        let mut second = Vec::new();
        init_with_paths(&repo.root, &config, &mut second).unwrap();

        assert_eq!(
            fs::read_to_string(repo.root.join(HOOKS_RELATIVE)).unwrap(),
            hooks_before
        );
        assert_eq!(fs::read_to_string(&config).unwrap(), config_before);
        assert!(String::from_utf8(second)
            .unwrap()
            .contains("already enabled"));
        // No backup files created when nothing changed.
        let backups = fs::read_dir(config.parent().unwrap())
            .unwrap()
            .filter_map(Result::ok)
            .filter(|entry| entry.file_name().to_string_lossy().contains("tractus-bak"))
            .count();
        assert_eq!(backups, 0);
    }

    #[test]
    fn preserves_existing_config_and_backs_up_before_editing() {
        let repo = TestRepo::new();
        let config = repo.root.join("config.toml");
        fs::write(
            &config,
            "# my settings\nmodel = \"gpt-5.6-terra\"\n\n[features]\nother = true\n",
        )
        .unwrap();
        let mut output = Vec::new();

        init_with_paths(&repo.root, &config, &mut output).unwrap();

        let updated = fs::read_to_string(&config).unwrap();
        assert!(updated.contains("model = \"gpt-5.6-terra\""));
        assert!(updated.contains("other = true"));
        assert!(updated.contains("hooks = true"));
        assert!(updated.contains("# my settings"));

        let backups = fs::read_dir(config.parent().unwrap())
            .unwrap()
            .filter_map(Result::ok)
            .filter(|entry| entry.file_name().to_string_lossy().contains("tractus-bak"))
            .count();
        assert_eq!(backups, 1);
    }

    #[test]
    fn missing_wrapper_is_an_error() {
        let repo = TestRepo::new();
        fs::remove_file(repo.root.join(WRAPPER_RELATIVE)).unwrap();
        let config = repo.root.join("config.toml");
        let mut output = Vec::new();

        assert!(matches!(
            init_with_paths(&repo.root, &config, &mut output),
            Err(InitError::WrapperMissing { .. })
        ));
    }
}
